version: 1
jobs:
  hello:
    steps:
      - echo "Hello"
  world:
    steps:
      - echo "World"
  hello-world:
    steps:
      - echo "Hello World!"
  test:
    runner: test
    steps:
      - echo "From test job"
stages:
  - name: build
    jobs:
      - - hello
        - world
      - hello-world
  - name: test
    jobs:
      - test
runners:
  test:
    config-id: 2