version: 1
jobs:
  hello:
    steps:
      - echo "Hello"
  world:
    steps:
      - npm install zcatalyst-cli
      - catalyst deploy
  hello-world:
    steps:
      - echo "Hello World!"
  test:
    runner: test
    steps:
      - echo "From test job"
  catalyst:
    runner: test
    steps:
      - npm install zcatalyst-cli
      - catalyst --version
      - catalyst deploy
stages:
  - name: catalyst
    jobs:
      - - hello
        - world

runners:
  test:
    config-id: 2