name: Create Release
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Loading Java17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Installing catalyst
        run : npm i -g zcatalyst-cli
      - name: Deploying code to catalyst
        working-directory: /aliencity
        run: catalyst deploy --project ${{ secrets.CATALYST_PROJECT_NAME}} --org ${{ secrets.CATALYST_ORG}} --token ${{ secrets.CATALYST_TOKEN}}
